#!/usr/bin/env python3
"""Generate the constant lookup tables used by pentagram.asm (writes tables.asm).

Angles are in "binary degrees": 256 units = 2*pi.
"""
import math
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tables.asm")


def rows(name, values, per_line=16):
    out = [f"{name}"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        out.append("        !byte " + ",".join(f"${v & 0xff:02x}" for v in chunk))
    return "\n".join(out)


lines = ["; generated by gen_tables.py -- do not edit", ""]

# |sin(theta)| * 255, theta in binary degrees
sinmag = [min(255, round(abs(math.sin(2 * math.pi * t / 256)) * 255)) for t in range(256)]
lines.append(rows("sinmag", sinmag))

# log2(n) * 32 (log2tab[0] is unused)
log2tab = [0] + [min(255, round(math.log2(n) * 32)) for n in range(1, 256)]
lines.append(rows("log2tab", log2tab))

# atan(2^(-n/32)) in binary degrees: atantab[0] = 32 (45 degrees)
atantab = [round(math.atan(2 ** (-n / 32)) * 256 / (2 * math.pi)) for n in range(256)]
lines.append(rows("atantab", atantab))

# Pentagram edges, matching PentaStar: vertex k sits at angle k*144 degrees,
# x = r*sin(a), y = r*cos(a).  The Java code walks x in steps of 1/fac where
# fac = clamp(|dy/dx|+1, 1, 2), so per-step increments are independent of r
# and the number of steps is r * |dx_unit| * fac.
e_vxmag, e_vxsgn, e_vymag, e_vysgn = [], [], [], []
e_xinclo, e_xinchi, e_yinclo, e_yinchi = [], [], [], []
e_cnlo, e_cnhi = [], []
for j in range(5):
    a0 = math.radians(j * 144)
    a1 = math.radians((j + 1) * 144)
    sx, sy = math.sin(a0), math.cos(a0)
    dx, dy = math.sin(a1) - sx, math.cos(a1) - sy
    fac = min(2.0, max(1.0, abs(dy / dx) + 1))
    xinc = math.copysign(1.0, dx) / fac
    yinc = xinc * dy / dx
    cn = abs(dx) * fac
    e_vxmag.append(min(255, round(abs(sx) * 255)))
    e_vxsgn.append(0x80 if sx < -1e-9 else 0)
    e_vymag.append(min(255, round(abs(sy) * 255)))
    e_vysgn.append(0x80 if sy < -1e-9 else 0)
    xi = round(xinc * 256) & 0xffff
    yi = round(yinc * 256) & 0xffff
    c = round(cn * 256)
    e_xinclo.append(xi & 0xff); e_xinchi.append(xi >> 8)
    e_yinclo.append(yi & 0xff); e_yinchi.append(yi >> 8)
    e_cnlo.append(c & 0xff); e_cnhi.append(c >> 8)

for name, vals in [("e_vxmag", e_vxmag), ("e_vxsgn", e_vxsgn),
                   ("e_vymag", e_vymag), ("e_vysgn", e_vysgn),
                   ("e_xinclo", e_xinclo), ("e_xinchi", e_xinchi),
                   ("e_yinclo", e_yinclo), ("e_yinchi", e_yinchi),
                   ("e_cnlo", e_cnlo), ("e_cnhi", e_cnhi)]:
    lines.append(rows(name, vals))

# trail amplitude factor: A_p = r * recip3p[p] / 256 = r / (3p)
recip3p = [round(256 / (3 * p)) for p in range(1, 8)]
lines.append(rows("recip3p", recip3p))

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
